/**
 * Top 100 Store
 */
Ext.define('Docs.store.Top100', {
    extend: 'Ext.data.Store',
    model: 'Docs.model.Top100',
    // Sort history with latest on top
    sorters: [
        { property: 'id', direction: 'DESC' }
    ],

    data: [{cls:'Ext.data.Store'},{cls:'Ext'},{cls:'Ext.grid.Panel'},{cls:'Ext.panel.Panel'},{cls:'getting_started'},{cls:'Ext.form.field.ComboBox'},{cls:'application_architecture'},{cls:'Ext.form.Panel'},{cls:'Ext.data.Model'},{cls:'Ext.button.Button'},{cls:'Ext.tree.Panel'},{cls:'Ext.Component'},{cls:'Ext.app.Application'},{cls:'Ext.window.Window'},{cls:'Ext.form.Basic'},{cls:'Ext.core.Element'},{cls:'Ext.form.field.Text'},{cls:'Ext.grid.column.Column'},{cls:'Ext.data.proxy.Ajax'},{cls:'Ext.container.Container'},{cls:'Ext.tab.Panel'},{cls:'Ext.data.proxy.Proxy'},{cls:'Ext.data.TreeStore'},{cls:'Ext.app.Controller'},{cls:'data'},{cls:'Ext.Ajax'},{cls:'class_system'},{cls:'Ext.grid.View'},{cls:'grid'},{cls:'Ext.data.reader.Json'},{cls:'Ext.AbstractComponent'},{cls:'Ext.container.Viewport'},{cls:'Ext.view.View'},{cls:'layouts_and_containers'},{cls:'Ext.toolbar.Toolbar'},{cls:'Ext.window.MessageBox'},{cls:'Ext.Loader'},{cls:'Ext.layout.Layout'},{cls:'Ext.chart.Chart'},{cls:'Ext.tree.View'},{cls:'Ext.form.field.Field'},{cls:'Ext.Base'},{cls:'Ext.data.reader.Reader'},{cls:'Ext.ComponentQuery'},{cls:'Ext.panel.Table'},{cls:'Ext.selection.Model'},{cls:'Ext.tab.Tab'},{cls:'Ext.menu.Menu'},{cls:'theming'},{cls:'Ext.grid.column.Action'},{cls:'Ext.form.field.Checkbox'},{cls:'Ext.data.Tree'},{cls:'Ext.grid.property.Grid'},{cls:'Ext.util.Observable'},{cls:'Ext.JSON'},{cls:'Ext.data.NodeInterface'},{cls:'Ext.layout.container.Border'},{cls:'Ext.data.Field'},{cls:'components'},{cls:'Ext.layout.container.HBox'},{cls:'Ext.form.FieldSet'},{cls:'tree'},{cls:'Ext.form.field.Base'},{cls:'Ext.XTemplate'},{cls:'Ext.Date'},{cls:'Ext.Class'},{cls:'Ext.form.Label'},{cls:'Ext.container.AbstractContainer'},{cls:'Ext.form.action.Action'},{cls:'Ext.form.field.Date'},{cls:'Ext.layout.container.VBox'},{cls:'drawing_and_charting'},{cls:'Ext.Array'},{cls:'Ext.data.proxy.Server'},{cls:'Ext.grid.plugin.RowEditing'},{cls:'Ext.ClassManager'},{cls:'Ext.data.proxy.Rest'},{cls:'Ext.layout.container.Card'},{cls:'Ext.data.AbstractStore'},{cls:'Ext.layout.container.Box'},{cls:'Ext.grid.plugin.CellEditing'},{cls:'Ext.form.FieldContainer'},{cls:'Ext.data.proxy.Direct'},{cls:'Ext.layout.container.Table'},{cls:'Ext.selection.RowModel'},{cls:'Ext.layout.container.Fit'},{cls:'Ext.ComponentLoader'},{cls:'Ext.grid.feature.Feature'},{cls:'Ext.layout.container.Anchor'},{cls:'Ext.toolbar.Paging'},{cls:'Ext.util.MixedCollection'},{cls:'Ext.Function'},{cls:'Ext.data.Operation'},{cls:'Ext.data.proxy.JsonP'},{cls:'Ext.form.field.TextArea'},{cls:'Ext.grid.header.Container'},{cls:'Ext.data.StoreManager'},{cls:'Ext.selection.CheckboxModel'},{cls: 'Ext.layout.container.Container'}]
});
